---
- hosts: all
  become: no
  become_user: root
  become_method: sudo
  vars:
    ruby_version: 2.3.1
    install_redis: yes
    install_postgres: yes
    install_mysql: yes
    install_sqlite: yes
  tasks:
    - name: Add Postgresql Repo
      become: yes
      apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
      when: install_postgres

    - name: Add Postgresql Repo Key
      become: yes
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state=present
      when: install_postgres

    - name: Locale step 1
      locale_gen: name=en_US.UTF-8 state=present

    - name: Locale step 2
      lineinfile: dest="~/.bashrc" line='export LANG="en_US.UTF-8"'

    - name: Update Apt Cache
      become: yes
      apt: update_cache=yes

    - name: Install Dependencies
      become: yes
      apt: name={{item}} install_recommends=yes
      with_items:
        - vim
        - git
        - git-core
        - curl
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - python-software-properties
        - libffi-dev

    - name: Install Nodejs Runtime
      become: yes
      apt: name={{item}} install_recommends=yes
      with_items:
        - nodejs
        - npm

    - name: Install Redis
      become: yes
      apt: name=redis-server install_recommends=yes
      when: install_redis

    - name: Install Sqlite
      become: yes
      apt: name={{ item }} install_recommends=yes
      with_items:
        - libsqlite3-dev
        - sqlite3
      when: install_sqlite

    - name: Configure mysql step 1
      shell: echo mysql-server mysql-server/root_password password vagrant | debconf-set-selections
      become: yes
      when: install_mysql

    - name: Configure mysql step 2
      shell: echo mysql-server mysql-server/root_password_again password vagrant | debconf-set-selections
      become: yes
      when: install_mysql

    - name: Install Mysql
      become: yes
      apt: name={{ item }} install_recommends=yes
      with_items:
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
        - python-mysqldb
      when: install_mysql

    - name: Set mysql root password
      mysql_user: name=root
                  password=""
                  check_implicit_admin=yes
                  login_user="root"
                  login_password="vagrant"
                  state=present
                  check_implicit_admin=yes
                  update_password=always
                  host={{ item }}
      with_items:
        - "127.0.0.1"
        - "::1"
        - "localhost"

    - name: Install Postgresql
      become: yes
      apt: name={{ item }} install_recommends=yes
      with_items:
        - postgresql-common
        - postgresql-9.4
        - libpq-dev
        - python-psycopg2
      when: install_postgres

    - name: Clone rbenv to ~/.rbenv
      git: repo=https://github.com/sstephenson/rbenv.git
        dest=~/.rbenv
        accept_hostkey=true
        force=yes

    - name: Clone ruby-build to ~/.rbenv
      git: repo=https://github.com/sstephenson/ruby-build.git
        dest="~/.rbenv/plugins/ruby-build"
        accept_hostkey=true
        force=yes

    - name: Clone rbenv-vars to ~/.rbenv
      git: repo=https://github.com/sstephenson/rbenv-vars.git
        dest="~/.rbenv/plugins/rbenv-vars"

    - name: Add rbenv To Profile
      template: src=templates/rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
      become: true

    - name: Check For Ruby {{ ruby_version }}
      shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
      register: ruby_installed
      changed_when: false
      ignore_errors: yes
      always_run: yes

    - name: Install Ruby
      shell: bash -lc "rbenv install {{ ruby_version }} && rbenv rehash"
      when:
        - ruby_installed.rc != 0

    - name: Set Global Ruby Version
      shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"
      when:
        - ruby_installed.rc != 0

    - name: Set .gemrc
      copy: src=files/gemrc dest=~/.gemrc

    - name: Install Bundler & Rails
      shell: bash -lc "gem install bundler rails"

    - name: cd to /vagrant on login
      lineinfile: dest="~/.bashrc" line="cd /vagrant"
